#pragma once

#include <initializer_list>
//#include <filesystem>
#include <cstdlib>
#include <fstream>
#include <cstdlib>
#include <utility>
#include <string>
#include <thread>
#include <chrono>
#include <vector>
#include <array>
#include <cmath>
#include <list>

#include <json/json.h>

#include <Qt>
#include <QApplication>
#include <QMessageBox>
#include <QtWidgets>
#include <QTimer>
#include <QListWidgetItem>
#include <QSerialPortInfo>
#include <QSerialPort>
#include <QVBoxLayout>
#include <QGridLayout>
#include <QRadioButton>
#include <QPushButton>
#include <QToolButton>
#include <QCloseEvent>
#include <QCheckBox>
#include <QTabWidget>
#include <QByteArray>
#include <QComboBox>
#include <QLineEdit>
#include <QSpinBox>
#include <QLabel>
#include <QPoint>
#include <QDebug>