	install(DIRECTORY ${CMAKE_SOURCE_DIR}/
	        DESTINATION SourceCode
			REGEX "/.vs" EXCLUDE
	        )
	install(DIRECTORY ${CMAKE_BINARY_DIR}/apps/ 
	        DESTINATION /
			REGEX "CMakeFiles|Odorator_autogen|translations" EXCLUDE
			)

set(CPACK_VERSION_MAJOR 0)
set(CPACK_VERSION_MINOR 10)
set(CPACK_VERSION_PATCH 7)
set(CPACK_PACKAGE_VERSION "${CPACK_VERSION_MAJOR}.${CPACK_VERSION_MINOR}.${CPACK_VERSION_PATCH}")
set(ORGANIZATION_NAME "ФГАОУ ВО «Южный федеральный университет»")
set(ORGANIZATION_URL "https://sfedu.ru/")
set(ORGANIZATION_EMAIL "ermolenkoav@yandex.ru")
set(CPACK_PACKAGE_VENDOR ${ORGANIZATION_NAME})

if(USE_NSIS)
	set(CPACK_GENERATOR NSIS)
	set(CPACK_NSIS_MODIFY_PATH OFF)
	set(CPACK_MONOLITHIC_INSTALL ON)
	set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
	set(CPACK_NSIS_PACKAGE_NAME "${PROJECT_NAME}")
	set(CPACK_NSIS_DISPLAY_NAME "${PROJECT_NAME}")
	set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROJECT_NAME}")
	set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "CreateShortCut \\\"$DESKTOP\\\\${PROJECT_NAME}.lnk\\\" \\\"$INSTDIR\\\\${PROJECT_NAME}.exe\\\"")
	set(CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "Delete \\\"$DESKTOP\\\\${PROJECT_NAME}.lnk\\\"")
	set(CPACK_NSIS_MUI_ICON ${PROJECT_SOURCE_DIR}/apps/${ORGANIZATION_LOGO})
	set(CPACK_NSIS_URL_INFO_ABOUT ${ORGANIZATION_URL})
	set(CPACK_NSIS_CONTACT ${ORGANIZATION_EMAIL})
	set(CPACK_NSIS_URL_INFO_ABOUT ${CPACK_PACKAGE_VENDOR})
else(USE_NSIS)
	set(CPACK_GENERATOR "ZIP")
endif(USE_NSIS)

if (ENABLE_CPACK)
	message("-- Enable CPack. cpack -C Release")
	include(CPack)
endif(ENABLE_CPACK)