name: C/C++ CI Linux-x64

on:
  push:
    branches:
      - master
      - dev
    tags:
      - '*.*.*'

#env:
#  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest

      - name: install dependencies
        run: sudo apt update && sudo apt install -y clang qt6-base-dev libqt6widgets6 libqt6openglwidgets6 libqt6serialport6-dev libpoco-dev libglx-dev libgl1-mesa-dev googletest

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          configurePresetAdditionalArgs: "['-DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++']"
          buildPreset: 'ninja-multi-vcpkg'
          buildPresetAdditionalArgs: "['--config Release']"
          testPreset: 'ninja-multi-vcpkg'
          testPresetAdditionalArgs: "['--config Release']"

      - name: Upload build folder
        uses: actions/upload-artifact@v2
        with:
          path: build/*.tar.gz
          name: artifact_${{ matrix.os }}_${{ matrix.configs }}.tar.gz
